AllCops:
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - log/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/*
    - db/schema.rb
  DisabledByDefault: true

Bundler/DuplicatedGem:
  Enabled: true

Bundler/InsecureProtocolSource:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Layout/ArgumentAlignment:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/DotPosition:
  EnforcedStyle: leading

Layout/EmptyComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true
  NumberOfEmptyLines: 1

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/IndentationStyle:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/LineLength:
  AllowedPatterns: [(\A|\s)#]
  Max: 100

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented_relative_to_receiver

Layout/ParameterAlignment:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideReferenceBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/ShadowedArgument:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Naming/PredicateName:
  Enabled: true

Naming/VariableName:
  EnforcedStyle: snake_case

Naming/InclusiveLanguage:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/EmptyElse:
  EnforcedStyle: both

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/GlobalVars:
  AllowedVariables: ["$rollout"]

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/NumericLiterals:
  MinDigits: 5
  Strict: false

Style/NumericPredicate:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StabbyLambdaParentheses:
  EnforcedStyle: require_parentheses

Style/StringConcatenation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true
